name: CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
        
      - name: Install Dependencies
        run: npm install

      - name: Run Test
        run: npm run test
        
  additional_steps:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Build the app
        run: npm run build
